### PR TITLE
[#3470] Fix enterprise repository name in SourceInfo

### LINKED ISSUE #3470: Fix enterprise repository name in SourceInfo
`SourceInfo` component in `Control Center` includes the wrong `repository name` for `enterprise `components (which affect the `install `requests)

SourcesInfo component call it `enterprise` when the backend expects `airy-enterprise`

### PR DESCRIPTION
**Pull request by AudreyKj**
closes #3470

### CODE REVIEW

File: frontend/control-center/src/components/SourceInfo/index.tsx [hunk 1]
```diff
@@ -192,7 +192,7 @@ export const getSourcesInfo = (): SourceInfo[] => {
       channelsListRoute: CONNECTORS_CONNECTED_ROUTE + '/salesforce',
       configKey: 'enterprise-salesforce-contacts-ingestion',
       componentName: 'salesforce-contacts-ingestion',
-      repository: 'enterprise',
+      repository: 'airy-enterprise',
```
Comment (AudreyKj) [inline frontend/control-center/src/components/SourceInfo/index.tsx:195]: repo name fix 💯

**Review by AitorAlgorta — APPROVED** [review]
