### PR TITLE
[#1652] Fix rendering messages with render library

### LINKED ISSUE #1652: Fix rendering messages with render library
**Current state** 
- There are a lot of messages that appear as "cannot render this content", especially for Google 

**To do**
- Investigate why so many messages are invalid 

Screenshot 2021-04-26 at 16 36 15

Screenshot 2021-04-29 at 10 19 07

### PR DESCRIPTION
**Pull request by AudreyKj**
closes #1652 

- the Inbound Suggestion Response messages from Google caused errors so couldn't be rendered because they are not nested in a `message` object

### CODE REVIEW

**Review by lucapette — APPROVED** [review]

**Review by thorstenairy — APPROVED** [review]

**Review by AitorAlgorta — APPROVED** [review]

File: lib/typescript/render/providers/google/GoogleRender.tsx [hunk 1]
```diff
@@ -51,7 +51,7 @@ function render(content: ContentUnion, props: RenderPropsUnion) {
 }
 
 function googleInbound(message: Message): ContentUnion {
-  const messageJson = message.content.message;
+  const messageJson = message.content.message ?? message.content;
```
Comment (chrismatix) [inline lib/typescript/render/providers/google/GoogleRender.tsx:54]: I'm not sure I understand how we got here? 🤔 If it's inbound the content should always have the same structure, right?

Comment (AudreyKj) [reply lib/typescript/render/providers/google/GoogleRender.tsx:54]: Yes! Except when the inbound messages are a`SuggestionResponse` (the user clicks on a Suggestion and sends it as a message). In this case, messages have a different structure (`message.content.suggestionResponse.text` instead of `message.content.message.text`)
