### PR TITLE
[#2791] Contacts service should be off by default

### LINKED ISSUE #2791: Contacts service should be off by default
## Describe the bug

Currently the `api-contacts` service starts by default with a new installation. This should not be the case.

## To Reproduce

1. Install and start a fresh Airy instance

## Expected behavior

To run contacts you have to configure it in the airy yaml first.

### PR DESCRIPTION
**Pull request by chrismatix**
resolves #2791

### CODE REVIEW

File: backend/api/contacts/src/main/java/co/airy/core/contacts/dto/Contact.java [hunk 1]
```diff
@@ -99,12 +99,12 @@ public Address merge(Address address) {
             }
 
             return this.toBuilder()
-                    .addressLine1(Optional.ofNullable(this.getAddressLine1()).orElse(address.getAddressLine1()))
```
Comment (chrismatix) [inline backend/api/contacts/src/main/java/co/airy/core/contacts/dto/Contact.java:102]: This was the wrong way around. Third time's a charm 😄

File: backend/api/contacts/src/test/java/co/airy/core/contacts/ImportContactsTest.java [hunk 2]
```diff
@@ -72,77 +60,57 @@ void beforeEach() throws Exception {
...
+                .andExpect(status().isCreated());
 
-        List<ContactResponsePayload> contactsResp = objectMapper.readValue(
-                importContent,
-                new TypeReference<List<ContactResponsePayload>>() {});
-
-        ContactsList cl = new ContactsList();
-        retryOnException(cl, "Not able to get contacts list");
-
-        final ListContactsResponsePayload contactsList = objectMapper.readValue(cl.getListContent(), ListContactsResponsePayload.class);
```
Comment (chrismatix) [inline backend/api/contacts/src/test/java/co/airy/core/contacts/ImportContactsTest.java:106]: Small refactor. Generally we try to avoid using our own payload POJOs to test APIs, because that way we don't check what clients actually receive.

File: backend/api/contacts/src/main/java/co/airy/core/contacts/dto/Contact.java (hunk 1 above)
Comment (juan-sebastian) [reply backend/api/contacts/src/main/java/co/airy/core/contacts/dto/Contact.java:102]: 🙈

**Review by juan-sebastian — APPROVED** [review]
Looks good to me
