### PR TITLE
[#1639] Fix conversation count

### LINKED ISSUE #1639: Fix Conversation count
**Current state** 
- there is. a bug in the way we count the conversations. We track the number of conversations with `conversations.length`, which results in a buggy behavior when there are lots of conversations 

**To do**
- fix counter

### PR DESCRIPTION
**Pull request by AitorAlgorta**
closes #1639

### CODE REVIEW

File: frontend/ui/src/pages/Channels/MainPage/index.tsx [hunk 1]
```diff
@@ -162,7 +162,9 @@ const MainPage = (props: MainPageProps & RouteComponentProps) => {
               sourceInfo={infoItem}
               displayButton={!channelsBySource(infoItem.type).length}
               addChannelAction={() => {
-                if (config.components[infoItem.configKey] && !config.components[infoItem.configKey].enabled) {
+                console.log(config.components[infoItem.configKey].enabled);
```
Comment (lucapette) [inline frontend/ui/src/pages/Channels/MainPage/index.tsx:165]: 💣

**Review by lucapette — APPROVED** [review]

**Review by lucapette — APPROVED** [review]
