### PR TITLE
[#1798] fix not rendered content messages in facebook render library

### LINKED ISSUE #1798: Fix not rendered content messages in Facebook render library
**Current State**
- there are still some messages that are not rendered in FB conversations (observed in Tedi, Endy, John Reed Instances)

Most not rendered content includes:
- fallback attachment 
- media template 

Screenshot 2021-05-17 at 16 10 00

### PR DESCRIPTION
**Pull request by AudreyKj**
closes #1798 

**Changes** 
- added [Media Template](https://developers.facebook.com/docs/messenger-platform/send-messages/template/media): 
- fixed fallback attachment
- fixed [Buttons](https://developers.facebook.com/docs/messenger-platform/reference/buttons) typings + added more button types
- created a Buttons component that is reused in all templates and supports all the types of buttons 

**Screenshots** 
Media Template: includes video or image (accepts only FB URLs so cannot be embedded) + buttons 
Screenshot 2021-05-21 at 11 40 03

### CODE REVIEW

File: lib/typescript/render/providers/facebook/FacebookRender.tsx [hunk 1]
```diff
@@ -73,32 +82,47 @@ function render(content: ContentUnion, props: RenderPropsUnion) {
...
+  if (attachment.type === 'template' && attachment.payload.template_type === 'media') {
+    return {
+      type: 'mediaTemplate',
+      media_type: attachment.payload.elements[0].media_type,
+      url: attachment.payload.elements[0].url ?? null,
+      attachment_id: attachment.payload.elements[0].attachment_id ?? null,
+      buttons: attachment.payload.elements[0].buttons,
+    };
+  }
+
```
Comment (AudreyKj) [inline lib/typescript/render/providers/facebook/FacebookRender.tsx:125]: Added Media Template: https://developers.facebook.com/docs/messenger-platform/reference/templates/media/

File: lib/typescript/render/providers/facebook/FacebookRender.tsx [hunk 2]
```diff
@@ -109,8 +133,8 @@ const parseAttachment = (attachment: SimpleAttachment | ButtonAttachment | Gener
   if (attachment.type === 'fallback') {
     return {
       type: 'fallback',
-      title: attachment.payload.title,
-      url: attachment.payload.url,
+      title: attachment.payload?.title ?? attachment.title,
+      url: attachment.payload?.url ?? attachment.url,
     };
   }
```
Comment (AudreyKj) [inline lib/typescript/render/providers/facebook/FacebookRender.tsx:139]: The fallback attachment does not always include the` title` and `url` in the `payload`: 
- https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/message-echoes/#fallback
- https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messages/

File: lib/typescript/render/providers/facebook/FacebookRender.tsx [hunk 3]
```diff
@@ -176,14 +202,14 @@ function facebookOutbound(message: Message): ContentUnion {
...
+  if (messageJson.attachment?.type === 'fallback' || messageJson.attachments?.[0].type === 'fallback') {
+    return {
+      text: messageJson.text ?? null,
+      ...parseAttachment(messageJson.attachment || messageJson.attachments[0]),
+    };
+  }
 
+  if (messageJson.attachment || messageJson.attachments) {
     return parseAttachment(messageJson.attachment || messageJson.attachments[0]);
   }
```
Comment (AudreyKj) [inline lib/typescript/render/providers/facebook/FacebookRender.tsx:215]: The message with fallback attachment can include a text (unlike other attachments)

- https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messages/

File: lib/typescript/render/providers/facebook/components/Buttons/index.tsx [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+              <div className={styles.buttonText}>Log Out</div>
+            ) : (
+              <div className={styles.buttonText}>{button.title}</div>
+            )}
+          </div>
+        );
+      })}
+    </>
+  );
+};
```
Comment (AudreyKj) [inline lib/typescript/render/providers/facebook/components/Buttons/index.tsx:32]: FB templates include a `buttons` array so I created a `Buttons ` component that is re-used

File: lib/typescript/render/providers/facebook/components/GenericTemplate/index.tsx [hunk 5]
```diff
@@ -19,19 +20,7 @@ export const GenericTemplate = ({template}: GenericTemplateRendererProps) => {
...
-                      {button.title}
-                    </a>
-                  ) : (
-                    <div className={styles.buttonText}>{button.title}</div>
-                  )}
-                </div>
-              );
-            })}
+            <Buttons buttons={element.buttons} />
           </div>
```
Comment (AudreyKj) [inline lib/typescript/render/providers/facebook/components/GenericTemplate/index.tsx:24]: here `Buttons` component in use

File: lib/typescript/render/providers/facebook/components/MediaTemplate/index.tsx [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+            see the {media_type} on Facebook
+          </a>
+        )}
+
+        {attachment_id && <span className={styles.mediaInfo}> {media_type} posted on Facebook</span>}
+      </div>
+      {buttons && <Buttons buttons={buttons} mediaTemplate={true} />}
+    </div>
+  );
+};
```
Comment (AudreyKj) [inline lib/typescript/render/providers/facebook/components/MediaTemplate/index.tsx:25]: Media Template component 
- media templates only accept FB URLs or FB ids so we cannot embed them 

https://developers.facebook.com/docs/messenger-platform/send-messages/template/media

File: lib/typescript/render/providers/facebook/facebookModel.ts [hunk 7]
```diff
@@ -3,9 +3,45 @@ export interface Attachment {
...
+
+export interface GamePlayButton extends Content {
+  type: 'game_play';
+  title: 'Play';
+  payload?: string;
+  game_metadata?: {
+    player_id?: string;
+    context_id?: string;
   };
 }
```
Comment (AudreyKj) [inline lib/typescript/render/providers/facebook/facebookModel.ts:46]: Refactored the typings of the Buttons + added more types 

- https://developers.facebook.com/docs/messenger-platform/reference/buttons

File: lib/typescript/render/providers/facebook/facebookModel.ts [hunk 8]
```diff
@@ -14,7 +50,7 @@ export interface ButtonAttachment extends Attachment {
   payload: {
     text: string;
     template_type: 'button';
-    buttons: Button[];
+    buttons: (URLButton | PostbackButton | CallButton | LoginButton | LogoutButton | GamePlayButton)[];
   };
```
Comment (AudreyKj) [inline lib/typescript/render/providers/facebook/facebookModel.ts:54]: Fixed the typing here: the messages templates include a `buttons` array that can accept different buttons (and not only web_url buttons)

https://developers.facebook.com/docs/messenger-platform/reference/buttons
