### PR TITLE
[#3723] Sort catalog by installed, name, price

### LINKED ISSUE #3723: Catalog card arrangement
## Describe the bug

Components that are ready to be installed comes as second priority after "Coming Soon" components. 

## To Reproduce

1. Open Control Center and click on Catalog. 
2. See error that "Coming soon" components appear in sequence before other available components for install.

## Expected behavior

Always showing components ready to Install first. 

## Environment

- Browser: [Chrome]
- Version: [Version 0.50.0-alpha]

### PR DESCRIPTION
**Pull request by thorstenairy**
closes #3723

### CODE REVIEW

File: frontend/control-center/src/pages/Catalog/index.tsx [hunk 1]
```diff
@@ -28,14 +34,19 @@ const Catalog = (props: ConnectedProps<typeof connector>) => {
...
+    const sortedByAccess = [...catalogList]
+      .filter((component: ComponentInfo) => component.price === ConnectorPrice.requestAccess)
+      .sort(sortByName);
 
-  const sortByInstall = (a: ComponentInfo) => {
-    if (a.installed) return 1;
-    return -1;
-  };
+    setOrderedCatalogList(sortedByInstalled.concat(sortedByUninstalled).concat(sortedByAccess));
+  }, [catalogList]);
```
Comment (AudreyKj) [inline frontend/control-center/src/pages/Catalog/index.tsx:50]: I understand that we are manipulating the DOM on each change, but I don't see a difference between useEffect and useLayoutEffect in this case (and useEffect is more performant).

**Review by AudreyKj — APPROVED** [review]
