### PR TITLE
[#1236] Fixed issues with filter by channel

### LINKED ISSUE #1236: SearchFields in filter for conversations in inbox are not displayed properly and not all names are displayed
Screenshot 2021-03-12 at 12 30 27

### PR DESCRIPTION
**Pull request by AitorAlgorta**
closes #1236

### CODE REVIEW

File: frontend/ui/src/components/IconChannelFilter/index.tsx [hunk 1]
```diff
@@ -6,12 +6,14 @@ import {ReactComponent as GoogleIcon} from 'assets/images/icons/google_avatar.sv
 import {ReactComponent as WhatsappIcon} from 'assets/images/icons/whatsapp_avatar.svg';
 import {ReactComponent as SmsIcon} from 'assets/images/icons/sms_avatar.svg';
 import {ReactComponent as FacebookIcon} from 'assets/images/icons/messenger_avatar.svg';
+import {ReactComponent as ChatPluginSource} from 'assets/images/icons/airy_avatar.svg';
```
Comment (lucapette) [inline frontend/ui/src/components/IconChannelFilter/index.tsx:9]: AiryAvatar? We should start at some point :)

Comment (AitorAlgorta) [reply frontend/ui/src/components/IconChannelFilter/index.tsx:9]: true dat

**Review by lucapette — APPROVED** [review]
