### PR TITLE
[#3560] control center remove sources info component

### LINKED ISSUE #3433: Update Control Center terminology
The terms we use in Control Center for some components and types is outdated and do not reflect our latest update of the glossary (for example `SourceInfo` should rather be called `ComponentsInfo` ect.)

- update terminology in the Control Center so that it reflects our current understanding of our glossary

### LINKED ISSUE #3560: Control Center: remove SourcesInfo component
**Current State:** 

Right now, in the Control Center, some parts rely on `SourcesInfo` and others on the `components.list` endpoint data (components.list endpoint was WP so that's why we still had to use the SourcesInfo component to populate some parts of the Control Center).

**To do**

When the components.list endpoint returns the right data, remove the `SourcesInfo` component and only rely on the data served by the `components.list` and `components.get` endpoints.

### LINKED ISSUE #3622: Webhook components doesn't appear on left nav bar when installed
## Describe the bug

On Control Center, on Catalog view, when "Webhooks" component is installed, the component configuration view on left navigation bar doesn't appear. 

## To Reproduce

1. Open Control Center, Catalog view. 
2. Find "Webhooks" compnent. 
3. See error that the component is installed but doesn't appear on left navigation bar for configuration. 
   3.1. see error when "Webhooks" component is not installed, the component configuration on left navigation 
         bar still appears. 
4. See another error that "open" button doesn't work; open webhook component configuration view. 

## Expected behavior

- When "Webhook" is installed, the comppnent should appear on left navigation bar for configuratiin. 
- When "Webhook" is not installed, the configuration component should not appear on left navigation bar. 

## Environment
- Browser: [Chrome]
- Version: [Version 0.49.0-alpha]

### LINKED ISSUE #3623: Webhook "To configure" error
## Describe the bug

On Control Center, on Catalog view, after installing "Webhooks" components, the "To configure" button action doesn't work. 

## To Reproduce

1. Open Control Center, Catalog view. 
2. Install "Webhooks" component. 
3. See error after installation, click on "To configure", it doesn't navigate to webhook configuration view. 

## Expected behavior

After installing "Webhooks" component, Airy user should be able to configure component from "To configure" button found on successful installation pop-up.

## Screenshots

FIG.1. NO ACTION TAKEN WHEN CLICKING "TO CONFIGURE" BUTTON. 

## Environment
- Browser: [Chrome]
- Version: [Version 0.49.0-alpha]

### PR DESCRIPTION
**Pull request by AudreyKj**
closes #3560 
closes #3433 
closes #3622 
closes #3623

### CODE REVIEW

File: frontend/control-center/src/components/Sidebar/index.tsx [hunk 1]
```diff
@@ -28,8 +29,10 @@ const Sidebar = (props: SideBarProps) => {
     return useMatch(`${route}/*`);
   };
 
-  const webhooksEnabled = props.components[ConfigServices.integrationWebhook]?.enabled || false;
-  const inboxEnabled = props.components[ConfigServices.frontendInbox]?.enabled || false;
+  const webhooksEnabled =
+    props.components[ConfigServices.integrationWebhook]?.enabled ||
+    props.catalog[`airy-core/${ConfigServices.integrationWebhook}`]?.installed === true;
+  const inboxEnabled = props.components[ConfigServices.frontendInbox]?.enabled;
   const showLine = inboxEnabled || webhooksEnabled;
```
Comment (AudreyKj) [inline frontend/control-center/src/components/Sidebar/index.tsx:37]: Webhooks appears in the sidebar when it is either enabled or installed

File: frontend/control-center/src/components/Sidebar/index.tsx [hunk 2]
```diff
@@ -28,8 +29,8 @@ const Sidebar = (props: SideBarProps) => {
     return useMatch(`${route}/*`);
   };
 
-  const webhooksEnabled = props.components[ConfigServices.integrationWebhook]?.enabled || false;
-  const inboxEnabled = props.components[ConfigServices.frontendInbox]?.enabled || false;
+  const webhooksEnabled = props.catalog[`airy-core/${ConfigServices.integrationWebhook}`]?.installed;
```
Comment (thorstenairy) [inline frontend/control-center/src/components/Sidebar/index.tsx:32]: we should create an enum for airy-core/airy-enterprise/airy-cloud

**Review by thorstenairy — APPROVED** [review]
🚀
