### PR TITLE
Fix chat plugin messaging behavior

### LINKED ISSUE #273: Chatplugin smoke test fixes
The smoke test revealed the following bugs in the chat plugin source:

- [x] Websocket messages are not filtered per source and conversation
- [x] The chat plugin does not mark messages sent from the inbox as delivered after sending it to the queue
- [x] We currently broadcast all messages to all users

### PR DESCRIPTION
**Pull request by chrismatix**
fixes #273

### CODE REVIEW

File: backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Principal.java [hunk 1]
```diff
@@ -13,6 +14,7 @@
 
     @Override
     public String getName() {
-        return sessionId;
+        // == conversation id
+        return UUIDV5.fromNamespaceAndName(channelId, sessionId).toString();
```
Comment (lucapette) [inline backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Principal.java:18]: probably over zealous _but_ we could generate in the constructor and return the cached value here

File: backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java [hunk 2]
```diff
@@ -42,9 +45,23 @@
...
                 .peek((messageId, message) -> webSocketController.onNewMessage(message));
 
+        messageStream.filter((messageId, message) -> !message.getSenderType().equals(SenderType.SOURCE_CONTACT)
+                && message.getDeliveryState().equals(DeliveryState.PENDING)
+        )
+                .mapValues((messageId, message) -> {
+                    message.setDeliveryState(DeliveryState.DELIVERED);
+                    webSocketController.onNewMessage(message);
+                    return message;
+                })
```
Comment (lucapette) [inline backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java:62]: if something goes wrong with the websocket, we end up not changing the state of the message so I'm thinking we should do the websocket part in a terminal node

**Review by lucapette — CHANGES_REQUESTED** [review]
Looking good! I think we have to address the topology as it's a simple change and will give the whole source better stability

**Review by lucapette — APPROVED** [review]
:shipit:
