### PR TITLE
[#3078] dialogflow to install and enable

### LINKED ISSUE #3078: Dialogflow - To install & Enable
In this ticket we are showing the UI of the dialogflow connector to be installed. The card is to be shown on "Catalog" view. 
{In progress}

1. Capture the current installation flow of this connector
2. Define the endpoint to automate connector deploy
3. Define connector config after installation; services/components names related to this connector. 

On Control Center, we need to create a design flow for all connector flow as mentioned below:

THIS DESIGN IS FOCUSED ON "DIALOGFLOW" CONNECTOR 

### FIRST: Uninstalled flow - design 

1. Connector is on Catalog.
2. User can click install without entering any info.
3. Connector is initially installed and moved to "Connector" view. 

### SECOND: Installed but not configured flow - design

4. Installed connector appears in "Catalog".
5. Connector has a tag e.g "Not configured".  
6. User clicks the connector card.
7. User configures the connector by entering connector prerequisites. e.g: for dialogflow connector the prerequisites are "Project_ID" & "Google cloud credentials".
8. User successfully configures the connector. 

### THIRD: To disable connector flow - design

9. User can "Disable" component from "Status" view.
10. User can "Disable" connector from "Connector" view - Card info.
11. User can "Disable" connector from "Catalog" view - connector card found under "Installed".

**### Successful user scenario:** 

1. System user is on Control Center. 
2. System user clicks on "Catalog".
3. System user see "Dialogflow" connector on catalog under "Uninstalled".
4. System user wants to install "Dialogflow" connector so one presses "Install" button found on the connector card.
5. Dialogflow connector is installed, card moved to "Installed".
6. On "Connectors" view, Dialogflow card appears with tag "Not configured" 
7. System user clicks on Dialogflow card, follow the configuration flow as follows: 
   7.1. Enter "Project_ID".
  7.2. Enter "Google Cloud Credentials", IF USER DOESN't HAVE THESE PERQUISITES  > provide "Getting started with Authentication : https://cloud.google.com/docs/authentication/getting-started".
  7.3. CONNECTOR_SUGGESTION_CONFIDENCE_LEVEL
  7.4. CONNECTOR_REPLY_CONFIDENCE_LEVEL
8. System user clicks "Configure"
10. Dialogflow is successfully enabled - popup message  
11. System user can find a link to navigate directly to "Dialogflow" project.
    11.1 A disable button to disable connector > go into idle mode to for example edit. 
    11.2 Internal Variables to adjust: 
       11.2.1. CONNECTOR_SUGGESTION_CONFIDENCE_LEVEL
       11.2.2 CONNECTOR_REPLY_CONFIDENCE_LEVEL

### FRONTEND TASKS:
 
1. Endpoint to access Airy controller's list of components and connectors.
2. Ability to initially install (install without config) > Install abstract for the connector with dummy/empty variables for prerequisites.
3. Ability to enable connector > add configuration.
4. Ability to edit the internal variables of the connector >
5. Ability to disable connector > uninstall and change status on Airy controller's components list.

### LINKED ISSUE #3228: Control center fix status view
## Describe the bug

Dropdown carets for the component status view conflict with the sidebar z-index

## Screenshots

image

## Environment

- OS: MacOs
- Browser: Chrome

### PR DESCRIPTION
**Pull request by AudreyKj**
closes #3078 
closes #3228 

**Changes:**
installed/uninstalled
reorganization of connectors / catalog  flow  + status update
dialogflow connector

**Note** install/uninstall is mocked, as it is not ready yet

### CODE REVIEW

File: frontend/control-center/src/reducers/data/config/index.ts [hunk 1]
```diff
@@ -19,13 +19,24 @@ const defaultState = {
...
+      return {
+        ...state,
+        components: {
+          ...state.components,
+          [action.payload.components[0].name]: {
+            ...state.components[action.payload.components[0].name],
+            enabled: action.payload.components[0].enabled,
+          },
+        },
+      };
```
Comment (AudreyKj) [inline frontend/control-center/src/reducers/data/config/index.ts:39]: Here added reducer for `enable/disable` component

File: lib/typescript/translations/translations.ts [hunk 2]
```diff
@@ -575,6 +607,19 @@ const resources = {
...
+      //Dialogflow
+      dialogflowDescription: 'Conversational AI mit virtuellen Agenten',
+      projectID: 'Projekt-ID',
+      AddProjectId: 'Projekt-ID hinzufügen',
+      GoogleApplicationCredentials: 'Google Application Credentials',
+      AddGoogleApplicationCredentials: 'Google Application Credentials hinzufügen',
+      SuggestionConfidenceLevel: 'Vorschlagsvertrauensniveau',
+      ReplyConfidenceLevel: 'Konfidenzniveau der Antwort',
+      to: 'bis',
+      fromCloudConsole: 'gegeben von das Cloud Console',
```
Comment (thorstenairy) [inline lib/typescript/translations/translations.ts:619]: gegeben von der Cloud Konsole

File: lib/typescript/translations/translations.ts [hunk 3]
```diff
@@ -575,6 +607,19 @@ const resources = {
...
+      amountSuggestions: 'betrag für Vorschläge',
```
Comment (thorstenairy) [inline lib/typescript/translations/translations.ts:620]: Anzahl der Vorschläge
