### PR TITLE
[#1497] media resolver crashes on bad configuration

### LINKED ISSUE #1497: Media Resolver crashes on bad configuration
### Current Behaviour
On startup, the media resolver app tries to build an AWS client based on the config values and that fails if they are invalid which results in the app crashing

### Expected Behaviour
The app should log that the configuration is invalid and not crash

### Example configuration which produced the error
```yaml
media-resolver:
    storage:
      s3:
        key: "changeme"
        secret: "changeme"
        bucket: "changeme"
        region: "changeme"
        path: "path"
```

### PR DESCRIPTION
**Pull request by juan-sebastian**
closes #1497 

Test if the connection is active and health on startup. if not sets the microservice as unhealthy (down)

### CODE REVIEW

File: backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java [hunk 1]
```diff
@@ -14,22 +19,30 @@
 import java.net.MalformedURLException;
 import java.net.URL;
 import java.net.URLConnection;
+import java.util.List;
 
 @Service
 @EnableRetry
 public class MediaUpload {
```
Comment (chrismatix) [inline backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java:26]: So the cool thing about healthchecks in Spring is that _any_ component can signal its healthy state. For instance `MediaUpload` can also implement the `HealthIndicator` interface. This way we don't need to query the `connectionStatus` variable from the `MediaController`

Sorry, I forgot to mention this. The rest of the code looks great 🙏

**Review by chrismatix — COMMENTED** [review]
Good implementation, minor nitpick about Spring 🙏

File: backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java (hunk 1 above)
Comment (juan-sebastian) [reply backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java]: Ok no worries, I moved the Heath check from `MediaController` to `MediaUpload`. Because there is no logic on the `MediaController` Heath implementation. I don't think it is necessary to have one on there

File: backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java [hunk 2]
```diff
@@ -14,22 +21,30 @@
...
+
     public MediaUpload(AmazonS3 amazonS3Client,
                        @Value("${s3.bucket}") String bucket,
                        @Value("${s3.path}") String path) throws MalformedURLException {
         this.amazonS3Client = amazonS3Client;
         this.bucket = bucket;
         this.path = appendSlash(path);
         this.host = new URL(String.format("https://%s.s3.amazonaws.com/", bucket));
+
+        // Check if the connection is healthy
```
Comment (pascal-airy) [inline backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java:46]: I'd try to limit the use of comments to when the logic is not deducible from the code

File: backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java [hunk 3]
```diff
@@ -59,4 +74,29 @@ private String resolveContentType(final String fileName, final InputStream is) t
...
+            List<Bucket> buckets = amazonS3Client.listBuckets();
+            if (buckets != null) {
+                log.info("check connection to S3 successful");
+                connectionStatus = true;
+            }
+        } catch (SdkClientException e) {
+            log.error("AWS SDK extension", e);
+
+        } catch (Exception e) {
+            log.error("unexpected extension", e);
```
Comment (pascal-airy) [inline backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java:90]: `extension` is that a typo?

**Review by pascal-airy — COMMENTED** [review]
Thanks for picking this one up!

File: backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java (hunk 2 above)
Comment (juan-sebastian) [reply backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java:46]: I think even if it is a bit redundant. That make it obvious and easier to the eye to see. In this case it easy to know that the check it is only done during the construction face.

File: backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java (hunk 3 above)
Comment (juan-sebastian) [reply backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java:90]: I wanted to write `exception` 🙈. I am bit dyslexic it won't be the last time this will happen 😅

File: backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java (hunk 2 above)
Comment (pascal-airy) [reply backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java]: Alright, I don't have a strong opinion so yours that you did the feature matter more :)

**Review by pascal-airy — APPROVED** [review]
lgtm!
