### PR TITLE
Fix/750 rename response metadata

### LINKED ISSUE #750: Rename ResponseMetadata
As we now have a metadata concept/model, this name is confusing. Suggestion: `PaginationData`

### PR DESCRIPTION
**Pull request by AudreyKj**
resolves #750 

BACKEND 
- Renamed response_metadata to pagination_data / paginationData

FRONTEND 
- Renamed all fields response_metadata to pagination_data
- Changed types in Actions of paginated endpoints (conversations + messages) using PaginatedPayload
- Changed types in Reducers of paginated endpoints (conversations + messages) 

HTTP TS LIBRRAY 
- Deleted ResponseMetadata from the lib 
- Exposed (exported) PaginatedPayload from the lib 

DOCS 
- Renamed response_metadata to pagination_data

### CODE REVIEW

**Review by chrismatix — DISMISSED** [review]
Ah, so that's why IntelliJ 😄  Good work!

File: lib/typescript/httpclient/payload/PaginatedPayload.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
 export interface PaginatedPayload<T> {
   data: T[];
-  response_metadata: {previous_cursor: string; next_cursor: string; total: number};
+  pagination_data: {previous_cursor: string; next_cursor: string; total: number};
```
Comment (lucapette) [inline lib/typescript/httpclient/payload/PaginatedPayload.ts:3]: I was waiting for this pr so we could fix the problems here. It's maybe a little annoying though. We'd need:

- change the casing so that it reflects JS conventions
- have a mapper in the library so that we can convert between two (even though... maybe there's already mappers and we can enrich them)

Comment (AudreyKj) [reply lib/typescript/httpclient/payload/PaginatedPayload.ts:3]: ok! fixing now

**Review by lucapette — APPROVED** [review]
:shipit:
