### PR TITLE
[#1306] Fix contact metadata problem

### LINKED ISSUE #1306: Fix fail contact metadata in inbox

### PR DESCRIPTION
**Pull request by AitorAlgorta**
closes #1306

### CODE REVIEW

File: frontend/ui/src/components/AiryWebsocket/index.tsx [hunk 1]
```diff
@@ -28,7 +29,8 @@ const mapDispatchToProps = dispatch => ({
   addMessages: (conversationId: string, messages: Message[]) => dispatch(addMessagesAction({conversationId, messages})),
   onChannel: (channel: Channel) => dispatch(setChannelAction(channel)),
   getConversationInfo: (conversationId: string) => dispatch(getConversationInfo(conversationId)),
-  onMetadata: (metadataEvent: MetadataEvent) => dispatch(setMetadataAction(metadataEvent)),
+  onMetadata: (metadataEvent: MetadataEvent) =>
+    dispatch(camelcaseKeys(setMetadataAction(metadataEvent), {deep: true, stopPaths: ['metadata.userData']})),
```
Comment (chrismatix) [inline frontend/ui/src/components/AiryWebsocket/index.tsx:33]: Sorry, I'm afraid it's `user_data` 🙈

**Review by lucapette — COMMENTED** [review]
:shipit:

**Review by chrismatix — DISMISSED** [review]

**Review by thorstenairy — APPROVED** [review]
LGTM

**Review by ogbeche77 — APPROVED** [review]
