### PR TITLE
[#2637] Fix channel prefill

### LINKED ISSUE #2637: Instagram: Edit Channel View in Inbox UI wrong prefill
## Describe the bug

The fields in the edit channel view for instagram in the Inbox UI are not prefilled correctly (not at all, respectively the Instagram ID is prefilled in the wrong input field).

Screenshot:

Screenshot 2021-12-07 at 14 11 25

## To Reproduce

1. Click on edit channel of type instagram in the Inbox UI
2. Look at the prefilled resp. empty form fields

## Expected behavior

- The Instagram ID is prefilled in the wrong form input field -> it should be prefilled in the Instagram ID input field, not in the Facebook Page ID field
- The Facebook Page ID field should be prefilled with the Facebook Page ID
- The token is empty which is confusing (but dependent of course on https://github.com/airyhq/airy/issues/2622) 

## Screenshots

See above

## Environment

- OS: MacOS
- Browser: Safari
- Version: latest

## Additional context

-

### PR DESCRIPTION
**Pull request by thorstenairy**
closes #2637

### CODE REVIEW

File: frontend/ui/src/AiryConfig.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
 export class AiryConfig {
   static NODE_ENV = process.env.NODE_ENV;
-  static FACEBOOK_APP_ID = 'CHANGE_ME';
+  static FACEBOOK_APP_ID = '1117544754977108';
```
Comment (chrismatix) [inline frontend/ui/src/AiryConfig.ts:3]: I'd remove the file alltogether as it's unused

**Review by AitorAlgorta — APPROVED** [review]
