### PR TITLE
[#3508] Fix empty state connectors

### LINKED ISSUE #3508: Update empty state connectors page
**Current state:**  The empty state of connectors page isn't accurate anymore, in the face of all the updates we did to control center

`To do: ` update the empty state of connectors page when no components are installed

### PR DESCRIPTION
**Pull request by thorstenairy**
closes #3508

### CODE REVIEW

File: frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx [hunk 1]
```diff
@@ -107,9 +127,16 @@ const CatalogItemDetails = (props: ConnectedProps<typeof connector>) => {
           <Button
             onClick={openModalInstall}
             className={styles.installButton}
+            disabled={isInstalling || isUninstalling}
             styleVariant={isInstalled ? 'warning' : 'green'}
           >
-            {isInstalled ? t('uninstall') : t('install')}
+            {isInstalling
+              ? t('installing')
```
Comment (AudreyKj) [inline frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx:134]: for French: installing ==>` installation...`

File: frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx [hunk 2]
```diff
@@ -59,21 +60,31 @@ type ConnectorConfigProps = {
...
+  const [isEnabled, setIsEnabled] = useState<boolean | null>(components[connectorInfo?.componentName]?.enabled);
   const [isConfigured, setIsConfigured] = useState(false);
   const [lineTitle, setLineTitle] = useState('');
   const [backTitle, setBackTitle] = useState('Connectors');
   const [backRoute, setBackRoute] = useState('');
   const {t} = useTranslation();
   const isInstalled = true;
 
+  console.log('SJAIDOJSAOIJDASOIDL ', components[connectorInfo?.componentName]?.enabled);
+
```
Comment (AudreyKj) [inline frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx:87]: console.log 💣

File: frontend/control-center/src/pages/Connectors/index.tsx [hunk 3]
```diff
@@ -113,15 +114,14 @@ const Connectors = (props: ConnectedProps<typeof connector>) => {
                   )) ||
                 (getSourceForComponent(infoItem.type) &&
                   components &&
-                  components[infoItem.configKey] &&
```
Comment (AudreyKj) [inline frontend/control-center/src/pages/Connectors/index.tsx:116]: this check is needed otherwise it can trigger an error 
Screenshot 2022-08-15 at 12 40 10
Screenshot 2022-08-15 at 12 40 44

File: frontend/control-center/src/pages/Webhooks/index.tsx [hunk 4]
```diff
@@ -96,29 +95,6 @@ const Webhooks = (props: WebhooksProps) => {
...
-          position: 'absolute',
-          left: '50%',
-          marginLeft: '-120px',
-          height: '40px',
-          width: '240px',
-          zIndex: 9999,
-          background: notifcationColor,
-          borderRadius: '10px',
-        }}
-      >
```
Comment (AudreyKj) [inline frontend/control-center/src/pages/Webhooks/index.tsx:116]: ❤️

File: lib/typescript/components/alerts/Notification/index.tsx [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+        <span className={styles.notificationText}>{text}</span>
+        {type === NotificationType.sticky && (
+          <div className={styles.stickyCloseButton} onClick={() => setClose(true)}>
+            <CloseIcon height={12} width={12} color="#FFFFFF" />
+          </div>
+        )}
+      </div>
+    </div>
+  );
+};
```
Comment (AudreyKj) [inline lib/typescript/components/alerts/Notification/index.tsx:81]: great component & sooo good to have this in the library 🚀

File: lib/typescript/components/alerts/Notification/index.tsx [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+  }, [close]);
+
+  return (
+    <div
+      ref={notificationRef}
+      className={`${styles.notificationContainer} ${
+        show && animType === NotificationType.fade ? styles.translateYAnimFade : styles.translateYAnimSticky
+      } ${close && styles.translateYAnimStickyClose}`}
+      style={{
+        background: successful === undefined || info ? '#1578d4' : successful ? '#0da36b' : '#d51548',
```
Comment (AudreyKj) [inline lib/typescript/components/alerts/Notification/index.tsx:66]: small nitpick: maybe use variables for the colors so that it's easy to understand what colors they are

File: lib/typescript/translations/translations.ts [hunk 7]
```diff
@@ -1064,8 +1083,18 @@ const resources = {
       update: 'Mise à jour',
       create: 'Créer',
       customize: 'Personnaliser',
+      successfullyEnabled: 'Activé avec succès',
+      successfullyDisabled: 'Désactivé avec succès',
+      failedEnabled: `Échec de l'activation`,
+      failedDisabled: 'Échec de la désactivation',
       install: 'Installer',
+      installing: 'Installer...',
```
Comment (AudreyKj) [inline lib/typescript/translations/translations.ts:1091]: 'Installation...' 🇫🇷

**Review by AudreyKj — APPROVED** [review]
great addition to the Control Center 🏆
