### PR TITLE
[3901 & 3900] Feature/3901 create kafka topic for components events

### LINKED ISSUE #3900: Concurrent installing new connectors leads to problems
## Describe the bug

When a user tries to install several connectors at the same time, the backend is unable to reset the cache properly which leads to further state issues. 

## To Reproduce

Steps to reproduce the behaviour:

1. Go to Control-Center
2. Go to Catalog
3. Try to connect multiple connectors concurrent

## Expected behaviour

The requested installs getting queued correctly and installed according the queue

### LINKED ISSUE #3901: Create Kafka topic for components events
We need to create a Kafka topic that streams, components events, like `installationStatus`

### PR DESCRIPTION
**Pull request by juan-sebastian**
closes #3901 
closes #3900

### CODE REVIEW

File: backend/components/installer/src/main/java/co/airy/core/api/components/installer/Stores.java [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+        storeComponent(cacheChanges);
+
+        prevoiusCacheMap = cacheStore
+            .entrySet()
+            .stream()
+            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
+    }
+
+    @Override
+    public Health health() {
```
Comment (chrismatix) [inline backend/components/installer/src/main/java/co/airy/core/api/components/installer/Stores.java:69]: nitpick: Remove as this health indicator does not do anything

File: backend/components/installer/src/test/java/co/airy/core/api/components/installer/CatalogHandlerTest.java [hunk 2]
```diff
@@ -89,88 +82,57 @@ static void afterAll() throws Exception {
...
-                .filter((c -> c.getName().equals("cognigy-connector")))
-                .findAny()
-                .orElse(null);
-            assertThat(cognigyConnector, is(notNullValue()));
-            assertThat(cognigyConnector.getInstallationStatus(), equalTo(InstallationStatus.uninstalled));
-        }
-
+        doReturn(getInstallationStatues()).when(installationStatusComponentsHandler).getInstallationStatusComponentsCache();
+
+        final List<ComponentDetails> listComponents = catalogHandler.listComponents();
```
Comment (chrismatix) [inline backend/components/installer/src/test/java/co/airy/core/api/components/installer/CatalogHandlerTest.java:91]: It would be great if we could mock this. Otherwise, this test might fail again if the data in the catalog changes. What do you think?

**Review by chrismatix — COMMENTED** [review]
Looks good! Minor comments

File: backend/components/installer/src/main/java/co/airy/core/api/components/installer/Stores.java (hunk 1 above)
Comment (juan-sebastian) [reply backend/components/installer/src/main/java/co/airy/core/api/components/installer/Stores.java:69]: But no class implements this interface. The health URL will still be instantiated by spring?

File: backend/components/installer/src/test/java/co/airy/core/api/components/installer/CatalogHandlerTest.java (hunk 2 above)
Comment (juan-sebastian) [reply backend/components/installer/src/test/java/co/airy/core/api/components/installer/CatalogHandlerTest.java:91]: Well this is an integration test. and I think the test should fail. If for example, someone does something wrong on the `catalog` page. Otherwise we have no way to know something went wrong until is in production. I will suggest to mock it when we have CI/Test for the catalog repo.
