### PR TITLE
fixed highlight in inbox

### LINKED ISSUE #1112: Inbox: highlight current conversation
The image below is the current view of the Inbox when a conversation is selected.

Screenshot 2021-03-01 at 14 17 26

The following image clearly shows which conversation is currently selected. We should outline or highlight the current conversation to make it easier to decipher which conversation the Airy user is currently in.
Screenshot 2021-03-01 at 14 21 09

### PR DESCRIPTION
**Pull request by AudreyKj**
resolves #1112 

fixed: highlights conversation when selected 
Screenshot 2021-03-03 at 08 39 55

### CODE REVIEW

File: frontend/ui/src/pages/Inbox/Messenger/index.tsx [hunk 1]
```diff
@@ -36,15 +36,19 @@ const Messenger = (props: ConnectedProps<typeof connector> & RouteComponentProps
...
+          <Fragment>
+            {!!conversations && (
+              <section className={styles.messengerContainerMiddlePanel}>
+                <ConversationList />
+              </section>
+            )}
+
+            <MessengerContainer {...props} />
+          </Fragment>
+        )}
```
Comment (AudreyKj) [inline frontend/ui/src/pages/Inbox/Messenger/index.tsx:51]: an alternative to including ConversationList in this route would be to fetch the conversation id from the pathname in ConversationList (as match.params.conversationId would not be available)

` const match: any = matchPath(ownProps.history.location.pathname, {
    path: '/inbox/conversations/:id',
  });
    currentConversationId: match && match.params.id,`

File: frontend/ui/src/pages/Inbox/Messenger/index.tsx [hunk 2]
```diff
@@ -36,15 +36,19 @@ const Messenger = (props: ConnectedProps<typeof connector> & RouteComponentProps
...
-        <section className={styles.messengerContainerMiddlePanel}>
-          <ConversationList />
-        </section>
-      )}
-
       <Route
         path={[`${match.url}/conversations/:conversationId`, `${match.url}`]}
-        render={props => <MessengerContainer {...props} />}
+        render={props => (
+          <Fragment>
```
Comment (AitorAlgorta) [inline frontend/ui/src/pages/Inbox/Messenger/index.tsx:42]: you can just use `<>`

**Review by AitorAlgorta — APPROVED** [review]

**Review by chrismatix — APPROVED** [review]
