### PR TITLE
[#1605] Fix Tags Flow

### LINKED ISSUE #1605: Tag color is always blue
### Current Behaviour

When creating a tag with another color (rather than the default blue), the assigned color is always blue 

### Expected behaviour

The created tag should have the selected color

new-tag

### PR DESCRIPTION
**Pull request by AitorAlgorta**
closes #1605

### CODE REVIEW

File: frontend/ui/src/pages/Tags/TableRow.tsx [hunk 1]
```diff
@@ -1,16 +1,20 @@
...
 import {Button, LinkButton} from 'components';
-import {ReactComponent as EditIcon} from 'assets/images/icons/edit.svg';
-import {ReactComponent as TrashIcon} from 'assets/images/icons/trash.svg';
 import ColorSelector from '../../components/ColorSelector';
 import Tag from '../../components/Tag';
 import {Tag as TagModel, TagColor} from 'model';
 import {Settings} from '../../reducers/data/settings';
 import {StateModel} from '../../reducers';
+
+import {ReactComponent as EditIcon} from 'assets/images/icons/edit-pencil.svg';
```
Comment (lucapette) [inline frontend/ui/src/pages/Tags/TableRow.tsx:13]: I suppose the "right" name would be `EditPencilIcon` (I know it was already there but since we're touching it...)

File: lib/typescript/httpclient/src/endpoints/listConversations.ts [hunk 2]
```diff
@@ -12,7 +12,7 @@ export const listConversationsDef = {
   },
   mapResponse: response => {
     const conversationData = (response as PaginatedPayload<any>).data.map(messagePayload => ({
-      ...camelcaseKeys(messagePayload, {deep: true, stopPaths: ['metadata.user_data']}),
+      ...camelcaseKeys(messagePayload, {deep: true, stopPaths: ['metadata.user_data', 'metadata.tags']}),
```
Comment (lucapette) [inline lib/typescript/httpclient/src/endpoints/listConversations.ts:15]: :angry-face:

Comment (lucapette) [reply lib/typescript/httpclient/src/endpoints/listConversations.ts:15]: is this the only place where we have this problem?

**Review by lucapette — APPROVED** [review]
Super minor comments.... looks great!

File: lib/typescript/httpclient/src/endpoints/listConversations.ts (hunk 2 above)
Comment (AitorAlgorta) [reply lib/typescript/httpclient/src/endpoints/listConversations.ts:15]: I tested a bit, and it looks that everything works fine now. But I can't say 100%.

File: frontend/ui/src/pages/Tags/TableRow.tsx (hunk 1 above)
Comment (AitorAlgorta) [reply frontend/ui/src/pages/Tags/TableRow.tsx:13]: I will change it

**Review by lucapette — APPROVED** [review]
