### PR TITLE
[#342] Add guide on how to connect Rasa and fix webhook API

### LINKED ISSUE #342: Introduce "how to set up a rasa connector"
We use raza as an "excuse" to show case our to integrate an airy webhook

### PR DESCRIPTION
**Pull request by chrismatix**
fixes #342

### CODE REVIEW

File: backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Mapper.java [hunk 1]
```diff
@@ -19,16 +21,23 @@
...
                 .id(message.getId())
-                .text(message.getContent())
+                .text(((Text) content).getText())
                 .source(message.getSource())
                 .postback(buildPostback(message))
                 .sentAt(isoFromMillis(message.getSentAt()))
-                .sender(new WebhookBody.Sender(message.getSenderId()))
+                .sender(WebhookBody.Sender.builder()
+                        .id(message.getSenderId())
+                        .type(message.getSenderType().toString().toLowerCase())
```
Comment (chrismatix) [inline backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Mapper.java:39]: Sources like Rasa need the sender type to know if they need to react to this message.

File: backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Mapper.java [hunk 2]
```diff
@@ -19,16 +21,23 @@
     }
 
     public WebhookBody fromMessage(Message message) throws Exception {
-        contentMapper.render(message);
```
Comment (chrismatix) [inline backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Mapper.java:22]: Gee someone completely forgot about this (yes it was me)
tenor

File: docs/docs/glossary.md [hunk 3]
```diff
@@ -77,9 +77,9 @@ Unique message id for deduplication.
 
 What type of actor inserted the message. One of:
 
-    - `SOURCE_CONTACT` sent to the source by a contact
-    - `SOURCE_USER` sent to the source by the user but not via app
-    - `APP_USER` sent to source via app
+    - `source_contact` sent to the source by a contact
```
Comment (chrismatix) [inline docs/docs/glossary.md:80]: Better to use the lower cased versions that are also used in payloads.

File: docs/docs/guides/airy-core-and-rasa.md [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+``` 
+
+Once you have done this, the Core Platform will start sending all messages to the
+url you specified.
+
+## Configuring Rasa
+
+Rasa comes with a default rest connector to consume HTTP webhooks. But since we 
+also want to use the Airy Api to respond to messages we will be implementing a
+[custom connector](https://rasa.com/docs/rasa/connectors/custom-connectors/).
```
Comment (lucapette) [inline docs/docs/guides/airy-core-and-rasa.md:51]:
```suggestion
We will be implementing a
[custom connector](https://rasa.com/docs/rasa/connectors/custom-connectors/) as we want to make use of the Airy Core Platform API.
```

File: docs/docs/guides/airy-core-and-rasa.md [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+
+For this we create a new directory `channels/` in our Rasa project and copy this
```
Comment (lucapette) [inline docs/docs/guides/airy-core-and-rasa.md:53]:
```suggestion
The first step is to create a new directory `channels/` in our Rasa project and copy this
```

File: docs/docs/guides/airy-core-and-rasa.md [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+[connector file](https://github.com/airyhq/rasa-demo/blob/master/channels/airy.py) into it. This Airy connector requires two configuration values to be set so that it can communicate
+with the Core Platform API:
```
Comment (lucapette) [inline docs/docs/guides/airy-core-and-rasa.md:55]:
```suggestion
[connector file](https://github.com/airyhq/rasa-demo/blob/master/channels/airy.py) into it. The connector requires the following configuration values: 
```

File: docs/docs/guides/airy-core-and-rasa.md [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+
+Rasa comes with a default rest connector to consume HTTP webhooks. But since we 
+also want to use the Airy Api to respond to messages we will be implementing a
+[custom connector](https://rasa.com/docs/rasa/connectors/custom-connectors/).
+
+For this we create a new directory `channels/` in our Rasa project and copy this
+[connector file](https://github.com/airyhq/rasa-demo/blob/master/channels/airy.py) into it. This Airy connector requires two configuration values to be set so that it can communicate
+with the Core Platform API: 
+
+- `auth_token`  This is the Airy Core Platform jwt token, which you used
```
Comment (lucapette) [inline docs/docs/guides/airy-core-and-rasa.md:57]:
```suggestion
- `auth_token`  the Airy Core Platform JWT token you used
```

File: docs/docs/guides/airy-core-and-rasa.md [hunk 8]
```diff
@@ -0,0 +1,71 @@
...
+                to connect the webhook.
+- `api_host`    The url, where you host your Airy Core Platform API. For a local installation
+                this would be `http://api.airy`.
```
Comment (lucapette) [inline docs/docs/guides/airy-core-and-rasa.md:60]:
```suggestion
- `api_host`    The url where you host your Airy Core Platform API (`http://api.airy` for a local installation).
```

File: docs/docs/guides/airy-core-and-rasa.md [hunk 9]
```diff
@@ -0,0 +1,71 @@
...
+
+Add these to your existing Rasa `credentials.yml` like so:
```
Comment (lucapette) [inline docs/docs/guides/airy-core-and-rasa.md:62]:
```suggestion
Add them to your existing Rasa `credentials.yml`:
```

File: docs/docs/guides/airy-core-and-rasa.md [hunk 10]
```diff
@@ -0,0 +1,71 @@
...
+
+```yaml
+channels.airy.AiryInput:
+  api_host: "your jwt authentication token"
```
Comment (lucapette) [inline docs/docs/guides/airy-core-and-rasa.md:66]:
```suggestion
  api_host: "your JWT authentication token"
```

File: docs/docs/guides/airy-core-and-rasa.md [hunk 11]
```diff
@@ -0,0 +1,71 @@
...
+  auth_token: "http://api.airy"
+``` 
+
+With this you are already done. To test the connection write a message to one of your sources
+that is recognized by your Rasa model.
```
Comment (lucapette) [inline docs/docs/guides/airy-core-and-rasa.md:71]:
```suggestion
Now you should have a working integration 🎉 . To test the connection write a message to one of the sources
recognized by your Rasa model.
```

File: docs/docs/sources/chat-plugin.md [hunk 12]
```diff
@@ -102,6 +102,9 @@ WebSocket connection handshake.
 
 #### Send message
 
+You have to set the `token` obtained on the [authorization endpoint](#authenticating-web-users) as an `Authorization`
```
Comment (lucapette) [inline docs/docs/sources/chat-plugin.md:105]:
```suggestion
You must set the `token` obtained on the [authorization endpoint](#authenticating-web-users) as an `Authorization`
```

**Review by lucapette — COMMENTED** [review]
First pass!

**Review by lucapette — APPROVED** [review]
