### PR TITLE
[#3249] fixed bug contacts

### LINKED ISSUE #3249: Page breaks when editing Contact "display_name" from Contacts entity
On Inbox, Contacts entity view, when a user open the edit mode to edit the contact display_name, it breaks. navigates to empty screen and can't go back to where i was editing.

The view where you can reproduce the issue:

### PR DESCRIPTION
**Pull request by AudreyKj**
closes #3249

### CODE REVIEW

File: frontend/inbox/src/pages/Contacts/ContactDetails/index.tsx [hunk 1]
```diff
@@ -56,7 +55,7 @@ const ContactDetails = (props: ContactDetailsProps) => {
   }, [cancelEditing]);
 
   const handleUpdateContact = () => {
-    updateContactDetails(conversationId, {id: contact.id, via: {email, phone}, title, organizationName: organization});
+    updateContactDetails({id: contact.id, via: {email, phone}, title, organizationName: organization});
   };
```
Comment (AudreyKj) [inline frontend/inbox/src/pages/Contacts/ContactDetails/index.tsx:59]: I removed the `conversationId` from the payload to update contact details because we're sorting contacts by contact id.

**Review by thorstenairy — APPROVED** [review]
LGTM
