### PR TITLE
[#3589] Retrieve installed components from cm

### LINKED ISSUE #3589: components.list returns installed=true for uninstalled component
## Describe the bug

When installing and then uninstalling a component, the `components.list` endpoint, still returns `"installed": true` for that component.

## To Reproduce

- inspect `components.list`  (installed = false)
- install a component (for example the chatplugin `{ "name": "airy-core/sources-chatplugin" }`)
- inspect `components.list` (installed = true)
- uninstall the component
- inspect `components.list` (still installed = true)

## Expected behavior

`installed` should be `false`.

## Screenshots

/

## Environment

All

## Additional context

/

### LINKED ISSUE #3599: components.install installs the latest chart in the repo
## Describe the bug

When installing a new component, the backend installs the latest helm chart in the repo, instead of instaling the version of the currently running `Airy Core` installation.

## To Reproduce

1. Create an Airy Core instance with version other then the latest develop
2. Install a new component
3. See with `helm list` how the versions of Airy Core and the component differ

## Expected behavior

As we agreed for now that the components will track the version of Airy Core, the new component (helm chart) should be installed with the same version.

## Screenshots

/

## Environment

- All

## Additional context

/

### PR DESCRIPTION
**Pull request by ljupcovangelski**
Instead of getting the installed helm charts and using the cache, I did a change where we fetch the installed components by retrieving the ConfigMaps which have the label `core.airy.co/component`.

With this change, I think that also the cache is not needed any more.

Resolves #3589.
Resolves #3599.

### CODE REVIEW

File: infrastructure/controller/pkg/endpoints/components_update.go [hunk 1]
```diff
@@ -40,10 +40,8 @@ func (s *ComponentsUpdate) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 
 	for _, component := range requestComponents.Components {
 		if !s.isComponentInstalled(component.Name) {
-			w.Header().Set("Content-Type", "application/json")
-			w.WriteHeader(http.StatusBadRequest)
-			w.Write([]byte(fmt.Sprintf(`{"error": "component %s is not installed"}`, component.Name)))
-			return
+			klog.Error("Trying to apply configuration for a component that is not installed: " + component.Name)
+			continue
```
Comment (ljupcovangelski) [inline infrastructure/controller/pkg/endpoints/components_update.go:44]: If there is a configuration in the `airy.yaml` file for at least one component that is not installed, the whole `airy config apply` command errors with a `Bad Request`. Therefore, I think that it is better if we just skip that component and at the end we return a list of components which have been updated.

File: infrastructure/controller/pkg/endpoints/components_install_uninstall.go [hunk 2]
```diff
@@ -46,13 +46,21 @@ func (s *ComponentsInstallUninstall) ServeHTTP(w http.ResponseWriter, r *http.Re
...
+	}
+
 	chartSpec := &helmCli.ChartSpec{
 		ReleaseName: releaseName,
 		ChartName:   chartName,
 		Namespace:   s.Namespace,
 		UpgradeCRDs: true,
 		Replace:     true,
 		Force:       true,
+		Version:     chart_version,
```
Comment (ljupcovangelski) [inline infrastructure/controller/pkg/endpoints/components_install_uninstall.go:63]: Install the same version of the component as the version of `Airy Core`.

File: docs/docs/getting-started/components.md [hunk 3]
```diff
@@ -73,6 +73,39 @@ Airy Core contains the following core components:
```
Comment (armanjindal) [inline docs/docs/getting-started/components.md:73]: Regarding the structure of the components page, I suggest we add the updated definition to the top of the page underneath the image. As you can see in PR #3558 I created a re-usable .mdx snippet for the definition. I would suggest adding this before we expose the cards.

File: docs/docs/getting-started/components.md [hunk 4]
```diff
@@ -73,6 +73,39 @@ Airy Core contains the following core components:
...
+- integration-webhook
+- media-resolver
+- sources-chatplugin
+- sources-facebook
+- sources-google
+- sources-twilio
+- sources-viber
+- sources-whatsapp
+
+However, you can also manage the components as helm charts. For example, to install the `sources-chatplugin` component, run this in your workspace:
```
Comment (armanjindal) [inline docs/docs/getting-started/components.md:101]: Do we not want users to download components via the Control Center? Or is this still under development? Do we prefer that they use the endpoints over the UI?

File: docs/docs/getting-started/components.md (hunk 3 above)
Comment (ljupcovangelski) [reply docs/docs/getting-started/components.md:73]: Sounds good :+1:. I will re-use the snippet from that PR :pray:

File: docs/docs/getting-started/components.md (hunk 4 above)
Comment (ljupcovangelski) [reply docs/docs/getting-started/components.md:102]: The `Control Center` is fully functional. I just thought of sharing additional info here, so that it is more clear how we install/uninstall them and as a failback if the UI fails.

Comment (ljupcovangelski) [reply docs/docs/getting-started/components.md:102]: Ah, I now see what you mean. The `Control center` should come as a first suggestion :). I will add this :+1:.

File: infrastructure/controller/pkg/endpoints/components_install_uninstall.go [hunk 5]
```diff
@@ -46,13 +46,21 @@ func (s *ComponentsInstallUninstall) ServeHTTP(w http.ResponseWriter, r *http.Re
 		return
 	}
 
+	chart_version, err := s.getVersion(r.Context())
```
Comment (chrismatix) [inline infrastructure/controller/pkg/endpoints/components_install_uninstall.go:49]: nitpick: This should be in camelCase

File: infrastructure/controller/pkg/endpoints/components_update.go (hunk 1 above)
Comment (chrismatix) [reply infrastructure/controller/pkg/endpoints/components_update.go:44]: I agree. Small suggestion: Could you add a single sentence about this to the HTTP API docs?

File: infrastructure/controller/pkg/endpoints/components_update.go [hunk 6]
```diff
@@ -71,7 +69,10 @@ func (s *ComponentsUpdate) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 
 //NOTE: Prevent the upload of a configmap if the component is not present
 func (s *ComponentsUpdate) isComponentInstalled(configName string) bool {
-	deployedCharts := s.DeployedCharts.GetDeployedCharts()
-
+	deployedCharts, err := k8s.GetInstalledComponents(context.TODO(), s.namespace, s.clientSet)
+	if err != nil {
+		klog.Error("Unable to get installed components:\n" + err.Error())
```
Comment (chrismatix) [inline infrastructure/controller/pkg/endpoints/components_update.go:74]: In the case of an error here the `/components.update` call should fail though, right? It means that there is something not right with the cluster. 

In any case this function should return the error so that we can differentiate between both cases 🤔

Comment (ljupcovangelski) [reply infrastructure/controller/pkg/endpoints/components_update.go:74]: Ok, in that case I will make the function return `bool,err` :+1:

**Review by chrismatix — APPROVED** [review]
