### PR TITLE
[#1450] Fix conversation counter

### LINKED ISSUE #1450: Bug: Inbox: Conversation Counter
Currently, the conversation counter does not update when a new message is received. The system user must reload the page in order for the number to update.

screenshot_2021-04-01_at_11 28 08

We need to automatically update the conversation counter when new messages are received, without requiring the user to reload the page.

### PR DESCRIPTION
**Pull request by thorstenairy**
closes #1450

### CODE REVIEW

File: frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx [hunk 1]
```diff
@@ -108,20 +111,21 @@ const ConversationsFilter = (props: ConversationsFilterProps) => {
...
     }
 
     if (conversationsPaginationData.total) {
       return (
         <div className={styles.filterCount}>
-          {`${formatter.format(
-            filteredPaginationData.filteredTotal || conversationsPaginationData.total
-          )} Conversations`}
+          {`${formatter.format(filteredPaginationData.filteredTotal || props.conversations.length)} Conversations`}
         </div>
```
Comment (AudreyKj) [inline frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx:129]: isn't `filteredPaginationData.filteredTotal` only supposed to be displayed in the first check?

Comment (AudreyKj) [inline frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx:129]: In the second check `(if (conversationsPaginationData.total))`, I guess there will always be a valid `filteredPaginationData.filteredTotal` 🤔

File: frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx [hunk 2]
```diff
@@ -108,20 +111,21 @@ const ConversationsFilter = (props: ConversationsFilterProps) => {
     const {conversationsPaginationData, filteredPaginationData} = props;
     const formatter = new Intl.NumberFormat('en-US');
 
-    if (filteredPaginationData.loaded) {
+    if (
+      filteredPaginationData.filteredTotal != undefined &&
+      filteredPaginationData.filteredTotal != filteredPaginationData.total
+    ) {
```
Comment (AudreyKj) [inline frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx:117]: minor comment: maybe here`!==` would be better for stricter check

**Review by AudreyKj — APPROVED** [review]
looks good to me!
